---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "treasurehunt.fullname" . }}-treasurehunt-secrets
type: Opaque
data:
  {{- if .Values.treasure.location.x }}
  treasure.location.x: {{ .Values.treasure.location.x | toString | b64enc | quote }}
  {{- else }}
  treasure.location.x: {{ mod (randNumeric 1) 4 | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.treasure.location.y }}
  treasure.location.y: {{ .Values.treasure.location.y | toString | b64enc | quote }}
  {{- else }}
  treasure.location.y: {{ mod (randNumeric 1) 5 | toString | b64enc | quote }}
  {{- end }}